
SELECT 
	 TABLE_NAME
	,COLUMN_NAME 
	,ORDINAL_POSITION
	,
	DATA_TYPE + 

	CASE
		WHEN DATA_TYPE LIKE '%varchar' AND CHARACTER_MAXIMUM_LENGTH = -1 THEN '(MAX)' 
		WHEN DATA_TYPE = 'varbinary' AND CHARACTER_MAXIMUM_LENGTH = -1 THEN '(MAX)' 
		ELSE ISNULL('(' + CAST(CHARACTER_MAXIMUM_LENGTH AS varchar(20)) + ')', '') 
	END 
	+
	CASE 
		WHEN IS_NULLABLE = 'YES' THEN ' NULL'
		ELSE ' not null'
		-- ELSE ''
	END 
	AS SQL_TYPE  

	,COLUMN_DEFAULT

	--,CHARACTER_MAXIMUM_LENGTH

	,
	CASE
		WHEN DATA_TYPE LIKE '%varchar' THEN 'string' 
		WHEN DATA_TYPE = 'int' THEN 'long' 
		WHEN DATA_TYPE = 'bit' THEN 'bool' 
		WHEN DATA_TYPE = 'datetime' THEN 'System.DateTime' 
		WHEN DATA_TYPE = 'date' THEN 'System.DateTime' 
		WHEN DATA_TYPE = 'float' THEN 'System.Decimal' 
		WHEN DATA_TYPE = 'bigint' THEN 'long' 
		WHEN DATA_TYPE = 'varbinary' THEN 'byte[]' 
		ELSE 'unknown' 
	END 
	+ 
	CASE 
		WHEN DATA_TYPE LIKE '%varchar' THEN '' 
		WHEN DATA_TYPE = 'varbinary' THEN '' 
		WHEN IS_NULLABLE = 'YES' THEN '?'
		ELSE ''
	END AS DOTNET_TYPE   

	--,*
FROM INFORMATION_SCHEMA.COLUMNS 
ORDER BY TABLE_NAME, ORDINAL_POSITION 



-- SELECT DISTINCT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS 
